### ISSUE TITLE
Broken on Python3

### ISSUE THREAD

**Issue by randomhammer** [coleifer/unqlite-python#15]
I installed the bindings on Python 3.4 and got the following:

```
Python 3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, 12:07:41)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import unqlite
>>> db = unqlite.UnQLite()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "unqlite.pyx", line 285, in unqlite.UnQLite.__init__ (unqlite.c:1888)
  File "unqlite.pyx", line 296, in unqlite.UnQLite.open (unqlite.c:2003)
TypeError: expected bytes, str found
>>>
```

Are the bindings not supported on Python 3 and I'm just missing it in the docs?

**Comment by coleifer** [comment]
No plans for py3k at the moment. I'll update the docs.

**Comment by randomhammer** [comment]
Thanks! Good thing I keep Python 2 around.  :)

**Comment by coleifer** [comment]
Check out #16 for a pull-request that has py3k compatibility changes. Not sure yet if I'll merge it due to performance considerations, but if it proves to be just as fast, then I will probably go ahead and merge.

**Comment by coleifer** [comment]
You can always just use that guys' branch, though.

**Comment by Cito** [comment]
I'm the guy with the Py 3 branch.

The problem with Python 3 is that its native strings are Unicode. UnQLite however deals only with byte strings, it does not have any concept of encoding.

So to faciliate usage in Python 3 and (also in Python 2 if you're using Unicode which you should), I decided to transparently encode/decode data on ingress/egress (using utf-8 encoding) and use the same interface for both, in a backward compatible way.

Because of this there is always an overhead of a type check.

I'm not really sure about the automatic conversion on egress. Currently I do this in Python 3, but not in Python 2. So you always get the native strings back.

If you have better ideas of dealing with the Unicode issue, let me know. Of course we could simply provide different methods or Classes for bytestring and unicode, but that would be ugly and error prone.
