### ISSUE TITLE
Iteration Run Time

### ISSUE THREAD

**Issue by PyDever** [coleifer/unqlite-python#41]
@coleifer To elaborate, numpy arrays are stored more efficientley in memory than regular Python tuples and list structures. I am merely suggesting you look into faster data structures and do more research into memory usage. :relaxed:. numpy can also store arbitrary length byte strings btw. also, my code is a for loop, what else lol

**Comment by coleifer** [comment]
I don't think you understand...

**Comment by PyDever** [comment]
Please clarify and enlighten me on these things that I apparently do not understand.

**Comment by PyDever** [comment]
Ignoring issues because **you** do not understand  is not a very good way to manage a project.

**Comment by coleifer** [comment]
You use an array because you can efficiently pack fixed length data like int4s into a single chunk. Using math u can index into it in O(1).

Numpy arrays are faster **while you're doing calculation** bc the in memory representation is optimized.

Unqlite deals with strings: variable length byte arrays. Wtf do u need numpy for, in other words. Or because you read and half understood something you think your issues signify a problem? No. Your issue signifies that you're an idiot.

**Comment by coleifer** [comment]
![im-a99b2ef29e](https://user-images.githubusercontent.com/119974/39106703-0686925a-4683-11e8-90f0-d2dcb1956e99.jpg)
